name: Running Code Coverage
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install && npm install c8

    - name: Run the tests
      run: npx c8 --reporter=lcov npm test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
